version: '3'

services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8006
    volumes:
      - .:/code
    ports:
      - "8006:8006"
#    depends_on:
#      - db
#
#  db:
#    image: mysql
#    restart: always
#    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
#    environment:
#      - MYSQL_HOST=172.18.0.1
#      - MYSQL_PORT=3306  # cannot change this port to other number
#      - MYSQL_DATABASE=InvoiceManagement # name you want for the database
#      - MYSQL_USER=newuser # change to whatever username you want
#      - MYSQL_PASSWORD=password #change to the password you want for user
#      - MYSQL_ROOT_PASSWORD=password #change to good root password
#    ports:
#      - "3306:3306"

