# Generated by Django 3.1.7 on 2021-03-01 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address_text', models.TextField()),
                ('website', models.CharField(max_length=120)),
                ('to_address_text', models.TextField()),
                ('company_name', models.CharField(max_length=120)),
                ('client_name', models.CharField(max_length=120)),
                ('invoice_number', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.client')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.company')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.project')),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='invoiceapp.client'),
        ),
        migrations.AlterField(
            model_name='address',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='invoiceapp.company'),
        ),
        migrations.CreateModel(
            name='Particular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField()),
                ('unit_rate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.invoice')),
            ],
        ),
    ]
