# Generated by Django 3.1.7 on 2021-03-02 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0002_auto_20210301_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='from_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_address', to='invoiceapp.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='to_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_address', to='invoiceapp.address'),
            preserve_default=False,
        ),
    ]
