# Generated by Django 3.1.7 on 2021-03-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0004_auto_20210302_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='particular',
            name='exchange_rate',
        ),
        migrations.AddField(
            model_name='invoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=3, default=70, max_digits=5),
            preserve_default=False,
        ),
    ]
