# Generated by Django 2.2.6 on 2021-03-09 09:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0008_company_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='agreement_detail',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='companyadditionalinfo',
            name='lut_bond',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='companyadditionalinfo',
            name='self_declaration',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='companyadditionalinfo',
            name='terms_condition',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
