# Generated by Django 3.1.3 on 2021-03-10 08:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0008_company_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='agreement_detail',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='companyadditionalinfo',
            name='lut_bond',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='companyadditionalinfo',
            name='self_declaration',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='companyadditionalinfo',
            name='terms_condition',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
