# Generated by Django 2.2.6 on 2021-03-10 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0010_auto_20210310_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyadditionalinfo',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.Company'),
        ),
        migrations.AlterField(
            model_name='companybankdetail',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.BankAccountType'),
        ),
        migrations.AlterField(
            model_name='companybankdetail',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.Company'),
        ),
    ]
