# Generated by Django 3.1.3 on 2021-03-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0011_auto_20210310_1859'),
        ('invoiceapp', '0009_auto_20210310_0837'),
    ]

    operations = [
    ]
