# Generated by Django 3.1.3 on 2021-03-12 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0014_auto_20210312_0816'),
        ('invoiceapp', '0014_invoice_name_of_person'),
    ]

    operations = [
    ]
