# Generated by Django 3.1.3 on 2021-03-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0015_merge_20210312_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='invoice_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_initial',
            field=models.CharField(default='sys-inv', max_length=50),
        ),
    ]
