# Generated by Django 3.1.3 on 2021-03-17 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0019_auto_20210317_0908'),
        ('invoiceapp', '0018_auto_20210317_0713'),
    ]

    operations = [
    ]
