# Generated by Django 3.1.3 on 2021-03-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0022_auto_20210318_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='company_cin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
