# Generated by Django 3.1.3 on 2021-03-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0023_invoice_company_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='eefc_account',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companybankdetail',
            name='branch_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='branch_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_eefc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
