# Generated by Django 3.1.3 on 2021-03-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0024_auto_20210319_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='eefc_account',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
