# Generated by Django 3.1.3 on 2021-03-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0025_auto_20210319_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='company_eefc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
