# Generated by Django 3.1.3 on 2021-05-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0027_auto_20210531_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='company_bank_acc_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_bank_acc_type_text',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_bank_ifsc_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='website',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
