# Generated by Django 2.2.6 on 2021-05-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0029_auto_20210531_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
