# Generated by Django 3.1.3 on 2021-06-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0030_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Paid', 'paid')], default='pending', max_length=20),
        ),
    ]
