# Generated by Django 3.1.3 on 2021-06-03 06:31

from django.db import migrations, models
import django.db.models.deletion

from invoiceapp.models import ResourceType


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0031_invoice_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='project_type',
            field=models.CharField(choices=[('fixed bid', 'Fixed Bid'), ('hourly', 'Hourly')], default='hourly', max_length=50),
        ),
        migrations.CreateModel(
            name='FixedBidParticular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_particulars_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=13)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.invoice')),
            ],
        ),
    ]
