# Generated by Django 2.2.6 on 2021-06-04 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0032_auto_20210603_0631'),
        ('invoiceapp', '0034_auto_20210604_0754'),
    ]

    operations = [
    ]
