# Generated by Django 3.1.3 on 2021-06-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0032_auto_20210603_0631'),
        ('invoiceapp', '0034_auto_20210604_0754'),
    ]

    operations = [
    ]
