# Generated by Django 3.1.3 on 2021-06-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0036_auto_20210604_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
