# Generated by Django 2.2.6 on 2021-06-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0035_merge_20210604_0909'),
        ('invoiceapp', '0037_auto_20210604_1024'),
    ]

    operations = [
    ]
