# Generated by Django 2.2.6 on 2021-06-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0038_merge_20210610_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='eefc_account',
        ),
    ]
