# Generated by Django 2.2.6 on 2021-06-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0039_remove_company_eefc_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankdetail',
            name='eefc_account',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
