# Generated by Django 2.2.6 on 2021-06-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0041_auto_20210610_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedbidparticular',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='particular',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='particular',
            name='unit_rate',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
