# Generated by Django 3.1.3 on 2021-06-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0042_auto_20210610_1709'),
        ('invoiceapp', '0042_auto_20210611_1040'),
    ]

    operations = [
    ]
