# Generated by Django 3.1.3 on 2021-06-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0043_merge_20210611_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='sub_unit',
            field=models.CharField(default='cent', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
    ]
