# Generated by Django 3.1.3 on 2021-06-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0044_auto_20210613_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='currency_unit',
            field=models.CharField(default='dollar', max_length=120),
            preserve_default=False,
        ),
    ]
