# Generated by Django 3.1.3 on 2021-07-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0046_auto_20210628_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='igst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
