# Generated by Django 3.1.3 on 2021-07-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0047_invoice_igst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particular',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
