# Generated by Django 3.1.3 on 2022-08-29 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0048_auto_20210705_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(blank=True, max_length=12, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=50, null=True)),
                ('project_type', models.CharField(choices=[('fixed price', 'Fixed Price'), ('hourly', 'Hourly')], default='hourly', max_length=50)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.project')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.resourcetype')),
            ],
        ),
        migrations.CreateModel(
            name='ParticularDeveloper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=13)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=13)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.developer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.invoice')),
            ],
        ),
    ]
