# Generated by Django 3.1.3 on 2022-09-06 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0049_developer_particulardeveloper'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.developer'),
        ),
    ]
