# Generated by Django 3.1.3 on 2022-09-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0050_invoice_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='developer',
        ),
        migrations.AddField(
            model_name='invoice',
            name='developer',
            field=models.ManyToManyField(related_name='developer', to='invoiceapp.Developer'),
        ),
    ]
