# Generated by Django 3.1.3 on 2022-09-15 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0051_auto_20220909_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedbidparticular',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.developer'),
        ),
        migrations.AddField(
            model_name='fixedbidparticular',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.project'),
        ),
        migrations.AddField(
            model_name='fixedbidparticular',
            name='resource_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.resourcetype'),
        ),
        migrations.AddField(
            model_name='particular',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.developer'),
        ),
        migrations.AddField(
            model_name='particular',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.project'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='developer',
            field=models.ManyToManyField(null=True, related_name='developer', to='invoiceapp.Developer'),
        ),
    ]
