# Generated by Django 3.2.5 on 2022-09-15 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0052_alter_invoice_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedbidparticular',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.developer'),
        ),
        migrations.AddField(
            model_name='fixedbidparticular',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.project'),
        ),
        migrations.AddField(
            model_name='fixedbidparticular',
            name='resource_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.resourcetype'),
        ),
        migrations.AddField(
            model_name='particular',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.developer'),
        ),
        migrations.AddField(
            model_name='particular',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.project'),
        ),
    ]
