# Generated by Django 3.2.5 on 2022-09-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0053_auto_20220915_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedbidparticular',
            name='project_particulars_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
