# Generated by Django 3.1.3 on 2022-09-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0054_alter_fixedbidparticular_project_particulars_name'),
        ('invoiceapp', '0052_auto_20220915_1405'),
    ]

    operations = [
    ]
